kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - protocol: TCP
    {{- if .Values.tls.enabled }}
    port: 443
    {{- else }}
    port: 80
    {{- end }}{{/* if .Values.tls.enabled */}}
    targetPort: 8443
