{{- if .Values.deployClusterServiceBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: service-broker
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}--{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{ if .Values.tls.enabled }}
  url: https://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- else }}
  url: http://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}{{/* if .Values.tls.enabled */}}
  insecureSkipTLSVerify: true
{{- if .Values.authenticate}}
  authInfo:
    bearer:
      secretRef:
        namespace: {{.Release.Namespace}}
        name: {{ template "fullname" . }}
{{- end }}
{{- end }}
