#!/usr/bin/env sh

set -e

wait_until() {
    until kubectl get pod --all-namespaces | grep "$2" | grep "$1" > /dev/null 2>&1; do
        echo "Waiting for '$2' ..."
        sleep 1
    done
}

kubectl create ns mysql || true
helm upgrade --install mysql bitnami/mysql --namespace mysql --set auth.rootPassword=secretpassword
wait_until "1\/1" "mysql-0"

kubectl create ns test-ns || true

kubectl apply -f ./manifests/mysql-database
wait_until "Completed" "binding-job"
wait_until "1\/1" "mysql-database"
kubectl delete -f ./manifests/mysql-database

kubectl delete ns test-ns
kubectl delete ns mysql