#!/usr/bin/env sh

set -e

wait_until() {
    until kubectl get pod --all-namespaces | grep "$2" | grep "$1" > /dev/null 2>&1; do
        echo "Waiting for '$2' ..."
        sleep 1
    done
}

kubectl create ns test-ns || true

kubectl apply -f ./manifests/mysql
wait_until "1\/1" "mysql-instance"
wait_until "Completed" "binding-job"
wait_until "1\/1" "wordpress"
kubectl delete -f ./manifests/mysql

kubectl delete ns test-ns
